runtime: python310

# Set instance class to ensure sufficient RAM
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  max_concurrent_requests: 50

# Handlers
handlers:
- url: /.*
  script: auto

# WSGI application entry point
entrypoint: gunicorn -k gthread -b :$PORT main:app

# Environment variables
env_variables:
  DOCKER_DEBUG: "1"
  PYTHONUNBUFFERED: "1"
  GRADIO_SERVER_PORT: "8080"

# Runtime configuration
runtime_config:
  python_version: "3.12"

